repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-json

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.38.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.38.0
          - typescript@5.0.4
          - eslint-config-standard@17.0.0
          - eslint-plugin-import@2.27.5
          - eslint-plugin-node@11.1.0
          - eslint-plugin-promise@6.1.1

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.8.7
    hooks:
      - id: prettier
        files: \.(js|ts|tsx|json|yml|yaml|md|html|css)$

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.12.0
    hooks:
      - id: markdownlint
        exclude: node_modules

  - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
    rev: v1.1.2
    hooks:
      - id: markdown-toc
        files: README\.md$
