# Project Documentation Hub - Jekyll Configuration
title: Project Documentation Hub
description: Central documentation for TypeScript SDK, Smart Contracts, RED X Backend, and Serverless Functions
baseurl: ""
url: ""

# Build settings
markdown: kramdown

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme

# Theme settings
theme: minima

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .gitignore
  - frontend/webapp/node_modules
  - "**/node_modules/**"
  - "**/.cache/**"
  - "**/dist/**"
  - "**/.git/**"
  - ts/node_modules

# Include specific files
include:
  - .nojekyll
  - .well-known
  - red_x/**/*.html
  - red_x/**/*.js
  - red_x/**/*.wasm
  - red_x/**/*.css
  - red_x/**/*.data
