# Site settings
title: StreamChain
description: A decentralized Web3 streaming platform powered by blockchain technology
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - package.json
  - package-lock.json
  - README.md
  - CNAME
  - .git
  - .github
  - server.js
