# Project RED X - Master Configuration File

# Site settings
title: Project RED X
description: A WebAssembly-powered graphics demo with Claude AI integration
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://idl3o.github.io/gh-pages" # the base hostname & protocol
author: Project RED X Team
email: contact@example.com
lang: en-US
timezone: UTC

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
encoding: utf-8
incremental: false
future: true

# Theme
theme: minima
remote_theme: jekyll/minima

# SEO settings
twitter:
  username: projectredx
  card: summary_large_image
logo: /assets/images/logo.png
social:
  name: Project RED X
  links:
    - https://github.com/idl3o/gh-pages
    - https://twitter.com/projectredx

# Project settings
project:
  name: Project RED X
  version: 1.0.1
  repository: https://github.com/idl3o/gh-pages
  documentation: https://idl3o.github.io/gh-pages/docs
  license: MIT

# Feature flags
features:
  educationPlatform: true
  digitalAssets: true
  cryptoStreaming: true
  web3Integration: true
  liveStreaming: false
  analyticsEnabled: true
  betaSignupEnabled: true

# Paths
paths:
  assets: /assets
  images: /assets/images
  css: /assets/css
  js: /assets/js
  docs: /docs
  pages: /pages
  data: /_data

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/
  docs:
    output: true
    permalink: /docs/:path/
  examples:
    output: true
    permalink: /examples/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "doc"
      sidebar: true
  - scope:
      path: "pages"
    values:
      layout: "page"
  - scope:
      path: "_posts"
    values:
      layout: "post"
      author: "Project RED X Team"
  - scope:
      path: "assets/images"
    values:
      image: true

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-titles-from-headings
  - jekyll-include-cache

# Performance optimization
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: [development]
  blanklines: false
  profile: false
  startings: [html, head, body]

# CDN settings
cdn:
  enabled: true
  provider: "jsdelivr"
  baseurl: "https://cdn.jsdelivr.net/gh/idl3o/gh-pages@main"

# Exclude from processing
exclude:
  - .git/
  - .github/
  - node_modules/
  - vendor/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - .gitignore
  - .eslintrc.js
  - .prettierrc
  - jest.config.js
  - package.json
  - package-lock.json
  - nodemon.json
  - setup-env.bat
  - windows-nvm-setup.md
  - tests/
  - scripts/
  - temp/

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-XXXXXXXX-X" # Replace with your tracking ID

# Include files/folders that would otherwise be excluded by Jekyll
include:
  - .well-known
