[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

# Redirect rule for SPA routing - redirects all paths to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200