name: Code Quality

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Add proper permissions for security scans
permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Generate lockfile if missing
        run: |
          if [ ! -f package-lock.json ]; then
            npm i --package-lock-only
          fi

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run lint
        run: npm run lint

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Generate lockfile if missing
        run: |
          if [ ! -f package-lock.json ]; then
            npm i --package-lock-only
          fi

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run npm audit
        run: npm audit --audit-level=high || true

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript
          config-file: .github/codeql-config.yml
          tools: latest

      - name: Build for CodeQL analysis
        run: npm run build

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:javascript"
