name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch all history for proper commits on deployment
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
          bundler-cache: true
          rubygems: 'latest'

      - name: Install dependencies
        run: |
          npm ci || npm install
          gem update --system
          bundle config set --local path 'vendor/bundle'
          bundle config set --local deployment 'true'
          bundle install --jobs 4 --retry 3

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run build and deploy script
        run: |
          chmod +x ./build-and-deploy.sh
          ./build-and-deploy.sh
        env:
          GITHUB_ACTIONS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JEKYLL_ENV: production

      # Debug step to verify _site directory
      - name: Debug _site directory
        run: |
          echo "Checking if _site directory exists..."
          if [ -d "_site" ]; then
            echo "_site directory exists"
            echo "Contents of _site directory:"
            ls -la _site
          else
            echo "ERROR: _site directory does not exist!"
            echo "Contents of current directory:"
            ls -la
            echo "Searching for build output directories:"
            find . -type d -name "_site" -o -name "dist" -o -name "build" -o -name "public"
          fi

      # Alternative deployment method using GitHub Pages Action
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '_site'
          # Ensure the path exists before uploading
          if-no-files-found: error

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        if: success()
