name: PowerShell Parameter Validation

on:
  push:
    branches: [main]
    paths:
      - '**.ps1'
      - '**.psm1'
      - '**.psd1'
  pull_request:
    branches: [main]
    paths:
      - '**.ps1'
      - '**.psm1'
      - '**.psd1'
  workflow_dispatch:

jobs:
  validate-powershell-params:
    name: Check for Parameter Naming Conflicts
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module -Name PSScriptAnalyzer -Force -Scope CurrentUser

      - name: Run PowerShell Parameter Validation
        shell: pwsh
        run: |
          Write-Host "Running PowerShell parameter name validation..."
          $Result = & ".\Check-PowerShellParameters.ps1"
          if ($LASTEXITCODE -ne 0) {
            Write-Host "::error::PowerShell parameter naming conflicts detected. Please run Check-PowerShellParameters.ps1 -Fix locally to fix them."
            exit 1
          }

      - name: Summary
        shell: pwsh
        run: |
          Write-Host "✅ PowerShell parameter validation passed. No naming conflicts detected."
