name: Unified Testing Workflow

on:
  push:
    branches: ['**']
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - '*.txt'
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      test_scope:
        description: 'Test scope'
        required: false
        default: 'all'
        type: choice
        options:
          - all
          - quick
          - compatibility
          - responsive

permissions:
  contents: read

jobs:
  lint:
    name: Code Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Validate PowerShell scripts
        if: runner.os == 'Windows'
        run: npm run validate_powershell
        continue-on-error: true

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run tests
        run: npm run test:ci

      - name: Run GitHub compatibility tests
        run: npm run test:github

      - name: Run security audit
        run: npm run test:security
        continue-on-error: true

  compatibility:
    name: Browser Compatibility
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.test_scope == 'all' || github.event.inputs.test_scope == 'compatibility') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run browser compatibility tests
        run: npm run test:browser-compat

      - name: Store compatibility report
        uses: actions/upload-artifact@v3
        with:
          name: compatibility-report
          path: reports/compatibility/
          retention-days: 7

  responsive:
    name: Responsive Design
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' && (github.event.inputs.test_scope == 'all' || github.event.inputs.test_scope == 'responsive') }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run responsive design tests
        run: npm run test:responsive

      - name: Store responsive screenshots
        uses: actions/upload-artifact@v3
        with:
          name: responsive-screenshots
          path: reports/screenshots/
          retention-days: 7

  verify-links:
    name: Verify Links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run link validation
        run: npm run test:links
        continue-on-error: true
