version: 2
updates:
  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    groups:
      dev-dependencies:
        patterns:
          - "eslint*"
          - "*prettier*"
          - "jest"
          - "nodemon"
    ignore:
      - dependency-name: "ethers"
        versions: ["6.x"]

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
