version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html
    networks:
      - web3-network
    # Alpine-based for minimal attack surface and size
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  dotnet-client:
    build:
      context: ./dotnet
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    networks:
      - web3-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
    # Using Alpine-based image from custom Dockerfile

  # New services using MCR Alpine-based images for better security and smaller size

  api-service:
    image: mcr.microsoft.com/dotnet/aspnet:6.0-alpine
    volumes:
      - ./dotnet/api-service/publish:/app
    working_dir: /app
    command: dotnet WebStreamApi.dll
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    networks:
      - web3-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M

  stream-processor:
    image: mcr.microsoft.com/dotnet/runtime:6.0-alpine
    volumes:
      - ./dotnet/stream-processor/publish:/app
    working_dir: /app
    command: dotnet StreamProcessor.dll
    environment:
      - ProcessorMode=Development
    networks:
      - web3-network
    restart: unless-stopped
    depends_on:
      - message-bus
    deploy:
      resources:
        limits:
          memory: 768M

  message-bus:
    image: rabbitmq:3-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=streamuser
      - RABBITMQ_DEFAULT_PASS=streampass
    ports:
      - "5672:5672"
    networks:
      - web3-network
    restart: unless-stopped
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 5s
      retries: 3

  monitoring:
    image: mcr.microsoft.com/dotnet/monitor:7
    environment:
      - DOTNETMONITOR_URLS=http://+:52323
    ports:
      - "52323:52323"
    volumes:
      - ./dotnet/monitoring-config:/config
    networks:
      - web3-network
    restart: unless-stopped

networks:
  web3-network:
    driver: bridge

volumes:
  rabbitmq_data:
