name: Deploy to GitHub Pages

on:
  push:
    branches: [main, master]
  workflow_dispatch: # Allow manual triggering

permissions:
  contents: write # Needed for gh-pages deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: |
          npm ci || npm install
          bundle install

      - name: Fix ESLint and Jekyll Issues
        run: |
          # Create necessary files if they don't exist
          if [ ! -f ".eslintignore" ]; then
            echo "_site/**
            .jekyll-cache/**
            vendor/**
            node_modules/**
            dist/**
            main_backup_*/**
            *.min.js" > .eslintignore
          fi

          # Fix Jekyll template errors
          chmod +x ./fix-jekyll-errors.sh || echo "No fix script found, skipping"
          ./fix-jekyll-errors.sh || echo "Fixing Jekyll errors failed, continuing"

      - name: Format and Lint
        run: |
          npx prettier --write . --ignore-path .eslintignore || echo "Prettier formatting skipped"
          npx eslint . --fix || echo "ESLint fixes skipped"
        continue-on-error: true

      - name: Build
        run: |
          # Set NODE_OPTIONS for Vite build compatibility
          export NODE_OPTIONS=--openssl-legacy-provider

          # Try full build first, fall back to Jekyll-only if needed
          npm run build || bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site # The folder the action should deploy
          branch: gh-pages # The branch the action should deploy to
          clean: true # Automatically remove deleted files
          single-commit: true # Create a single commit instead of maintaining history
          git-config-name: GitHub Actions
          git-config-email: github-actions@github.com
          commit-message: "Deploy website - ${GITHUB_SHA}"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: _site

      - name: Deployment Results
        run: |
          echo "Site built and deployed to gh-pages branch."
          echo "View your site at https://${{ github.repository_owner }}.github.io/$(echo ${{ github.repository }} | cut -d'/' -f2)/"
