name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering

# Prevent concurrent deployments
concurrency:
  group: pages-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: true
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'

    # Simplified dependency installation to avoid the lock file error
    - name: Install dependencies
      run: npm install

    - name: Setup Ruby for Jekyll
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.1'
        bundler-cache: true

    - name: Install Jekyll and dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build site
      run: npm run build
      env:
        JEKYLL_ENV: production

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        folder: _site
        clean: true
        token: ${{ secrets.GITHUB_TOKEN }}
