name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  # Allow manual triggering of the workflow
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch all history for proper commits on deployment
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install dependencies
        run: |
          npm ci || npm install
          bundle install

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Run build and deploy script
        run: |
          chmod +x ./build-and-deploy.sh
          ./build-and-deploy.sh
        env:
          GITHUB_ACTIONS: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Alternative deployment method using GitHub Pages Action
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '_site'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
        if: success()
