name: GitHub Compatibility Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Run weekly on Mondays

jobs:
  compatibility-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Run linting
        run: npm run lint
        continue-on-error: true

      - name: Run tests
        run: npm run test:ci

      - name: Test build process
        run: npm run build

      - name: Verify GitHub Pages compatibility
        run: npm run verify:github

  browser-compatibility:
    runs-on: ubuntu-latest
    needs: compatibility-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build site
        run: npm run build

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium firefox webkit
        continue-on-error: true

      - name: Run browser compatibility tests
        run: npm run test:browsers || echo "Browser tests skipped"
        continue-on-error: true

  links-validation:
    runs-on: ubuntu-latest
    needs: compatibility-test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci || npm install

      - name: Build site
        run: npm run build

      - name: Check for broken links
        run: npm run test:links || echo "Link checking skipped"
        continue-on-error: true
```
