name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'

      - name: Install Node dependencies
        run: npm ci || npm install

      # Simplified Ruby setup to avoid bundler-cache issues
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false
        continue-on-error: true

      - name: Install Bundler manually
        run: |
          gem install bundler -v 2.3.26
          bundle config set --local path 'vendor/bundle'
        continue-on-error: true

      - name: Install Ruby dependencies manually
        run: |
          if [ -f "Gemfile" ]; then
            bundle install --jobs=4 --retry=3 || echo "Bundle install failed, continuing without Ruby dependencies"
          else
            echo "No Gemfile found, skipping bundle install"
          fi
        continue-on-error: true

      - name: Run tests
        run: npm test
        continue-on-error: true

      - name: Build
        run: npm run build
        env:
          SKIP_JEKYLL: 'true' # Set environment variable to skip Jekyll if needed

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
