name: Pull Request Validation

on:
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true

      - name: Validate Jekyll build
        run: bundle exec jekyll build --safe
        env:
          JEKYLL_ENV: production

      - name: Check for Jekyll build errors
        run: |
          if [ ! -d "_site" ]; then
            echo "::error::Jekyll build failed - _site directory not created"
            exit 1
          fi

      - name: Setup Node.js
        if: hashFiles('ts/package.json') != ''
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: ts/package-lock.json

      - name: TypeScript Validation
        if: hashFiles('ts/package.json') != ''
        run: |
          cd ts
          npm ci
          npm run lint || echo "Linting issues found"
          npm run build