name: Pull Request Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: cd java/serverless-function && mvn -B package --file pom.xml

      - name: Run Java tests
        run: cd java/serverless-function && mvn -B test

  validate-static-site:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # HTML validation
      - name: HTML validation
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: .
          format: text
          log_level: INFO

  security-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Maven dependency security check
        run: |
          cd java/serverless-function
          mvn org.owasp:dependency-check-maven:check

      # Only run npm audit if package.json exists
      - name: Check for package.json
        id: check_package
        run: |
          if [ -f "package.json" ]; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: JavaScript dependency security check
        if: steps.check_package.outputs.exists == 'true'
        run: |
          npm audit || true
        continue-on-error: true  # Continue even if npm audit finds issues
