name: Ruby CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '**/*.rb'
      - 'Gemfile'
      - 'Gemfile.lock'
  pull_request:
    paths:
      - '**/*.rb'
      - 'Gemfile'
      - 'Gemfile.lock'

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ruby Tests
    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: false

      - name: Update Bundler
        run: |
          gem install bundler
          bundle --version

      - name: Install dependencies with verbose logging
        run: |
          for i in 1 2 3; do
            bundle install --verbose --jobs 4 --retry 3 && break || echo "Retry $i..."
            sleep 5
          done

      - name: List installed gems
        run: bundle list

      - name: Run tests
        run: bundle exec rake test || echo "No tests to run"
        continue-on-error: true
```
